// AUTO-GENERATED by scripts/generate_translations build step. Do not edit by hand.
// Maps language code -> { translationKey: translatedString } for AI-generated locales.
import l_af from "./af.json";
import l_am from "./am.json";
import l_as from "./as.json";
import l_az from "./az.json";
import l_be from "./be.json";
import l_bg from "./bg.json";
import l_bs from "./bs.json";
import l_ca from "./ca.json";
import l_ckb from "./ckb.json";
import l_cs from "./cs.json";
import l_cy from "./cy.json";
import l_da from "./da.json";
import l_el from "./el.json";
import l_et from "./et.json";
import l_eu from "./eu.json";
import l_fa from "./fa.json";
import l_fi from "./fi.json";
import l_fil from "./fil.json";
import l_ga from "./ga.json";
import l_gl from "./gl.json";
import l_gu from "./gu.json";
import l_ha from "./ha.json";
import l_he from "./he.json";
import l_hr from "./hr.json";
import l_hu from "./hu.json";
import l_hy from "./hy.json";
import l_id from "./id.json";
import l_ig from "./ig.json";
import l_is from "./is.json";
import l_it from "./it.json";
import l_ja from "./ja.json";
import l_ka from "./ka.json";
import l_kk from "./kk.json";
import l_km from "./km.json";
import l_kn from "./kn.json";
import l_ko from "./ko.json";
import l_ky from "./ky.json";
import l_lb from "./lb.json";
import l_lo from "./lo.json";
import l_lt from "./lt.json";
import l_lv from "./lv.json";
import l_mg from "./mg.json";
import l_mk from "./mk.json";
import l_ml from "./ml.json";
import l_mn from "./mn.json";
import l_mr from "./mr.json";
import l_ms from "./ms.json";
import l_mt from "./mt.json";
import l_my from "./my.json";
import l_ne from "./ne.json";
import l_nl from "./nl.json";
import l_no from "./no.json";
import l_ny from "./ny.json";
import l_or from "./or.json";
import l_pa from "./pa.json";
import l_pl from "./pl.json";
import l_ps from "./ps.json";
import l_ro from "./ro.json";
import l_rw from "./rw.json";
import l_sd from "./sd.json";
import l_si from "./si.json";
import l_sk from "./sk.json";
import l_sl from "./sl.json";
import l_sn from "./sn.json";
import l_so from "./so.json";
import l_sq from "./sq.json";
import l_sr from "./sr.json";
import l_st from "./st.json";
import l_sv from "./sv.json";
import l_sw from "./sw.json";
import l_ta from "./ta.json";
import l_te from "./te.json";
import l_tg from "./tg.json";
import l_th from "./th.json";
import l_tk from "./tk.json";
import l_tr from "./tr.json";
import l_uk from "./uk.json";
import l_uz from "./uz.json";
import l_vi from "./vi.json";
import l_xh from "./xh.json";
import l_yo from "./yo.json";
import l_zu from "./zu.json";

const GENERATED = {
  "af": l_af,
  "am": l_am,
  "as": l_as,
  "az": l_az,
  "be": l_be,
  "bg": l_bg,
  "bs": l_bs,
  "ca": l_ca,
  "ckb": l_ckb,
  "cs": l_cs,
  "cy": l_cy,
  "da": l_da,
  "el": l_el,
  "et": l_et,
  "eu": l_eu,
  "fa": l_fa,
  "fi": l_fi,
  "fil": l_fil,
  "ga": l_ga,
  "gl": l_gl,
  "gu": l_gu,
  "ha": l_ha,
  "he": l_he,
  "hr": l_hr,
  "hu": l_hu,
  "hy": l_hy,
  "id": l_id,
  "ig": l_ig,
  "is": l_is,
  "it": l_it,
  "ja": l_ja,
  "ka": l_ka,
  "kk": l_kk,
  "km": l_km,
  "kn": l_kn,
  "ko": l_ko,
  "ky": l_ky,
  "lb": l_lb,
  "lo": l_lo,
  "lt": l_lt,
  "lv": l_lv,
  "mg": l_mg,
  "mk": l_mk,
  "ml": l_ml,
  "mn": l_mn,
  "mr": l_mr,
  "ms": l_ms,
  "mt": l_mt,
  "my": l_my,
  "ne": l_ne,
  "nl": l_nl,
  "no": l_no,
  "ny": l_ny,
  "or": l_or,
  "pa": l_pa,
  "pl": l_pl,
  "ps": l_ps,
  "ro": l_ro,
  "rw": l_rw,
  "sd": l_sd,
  "si": l_si,
  "sk": l_sk,
  "sl": l_sl,
  "sn": l_sn,
  "so": l_so,
  "sq": l_sq,
  "sr": l_sr,
  "st": l_st,
  "sv": l_sv,
  "sw": l_sw,
  "ta": l_ta,
  "te": l_te,
  "tg": l_tg,
  "th": l_th,
  "tk": l_tk,
  "tr": l_tr,
  "uk": l_uk,
  "uz": l_uz,
  "vi": l_vi,
  "xh": l_xh,
  "yo": l_yo,
  "zu": l_zu,
};

export default GENERATED;
